version: "3.9"

services:
  web:
    build: 
      context: ./back
      dockerfile: Dockerfile
    command: gunicorn server.wsgi:application --bind 0.0.0.0:8000 --workers 3
    expose:
      - 8000
      
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./back/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web