apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  nginx.conf: |-
    events {}

    http {
        upstream django {
            server django-service:8000;
        }

        server {
            listen 80;

            location / {
                proxy_pass http://django-service:8000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location /static/ {
                alias /usr/src/app/static/;
            }
        }
    }
